### ISSUE TITLE
overwritten - can't prevent innoextract from overwriting files

### ISSUE THREAD

**Issue by ghostlyghastly** [dscharrer/innoextract#140]
Amazing tool, thank you but it looks like files have source and target paths but for example fallout nevada overwrites dialog files depending on the language you chose in the installer.

--dump still overwrites files

Installer used: (legal link, this is an independent mod and does not contain the original game) https://www.mediafire.com/file/nqfrkb5fllbpqx4/Fallout_Nevada_Mod_Us.exe/file Link from

**Comment by Kazurin-775** [comment]
Maybe I've been a little late, but it turns out that you could pass `--collisions rename-all` to make the application keep all files with the same paths, as [documented in the application's man page](https://github.com/dscharrer/innoextract/blob/325a7c965512d6d4a36afc48bed3e60a933bd111/doc/innoextract.1.in#L107).

This option seems to have existed for quite long, but it just isn't well documented in the application's `--help`.

**Comment by dscharrer** [comment]
Right, `--collisions rename` or `--collisions rename-all` is what you want to use to keep all versions of the same file. The `--help` output is autogenerated and only provides a quick reference of the available options - the man page included with innoextract or [the online version](https://constexpr.org/innoextract/innoextract.1) has more details.
