### ISSUE TITLE
Innoextract doesn't extract multiple install files

### ISSUE THREAD

**Issue by TimorLee** [dscharrer/innoextract#37]
I tried to extract the GOG Installer for Divinity: Original Sin but innoextract just extracts the.exe file (I think), not the 3 .bin files that are part of the install. The files on GOG are:
setup_divinity_original_sin_2.5.0.11.exe 
setup_divinity_original_sin_2.5.0.11-1.bin 
setup_divinity_original_sin_2.5.0.11-2.bin 
setup_divinity_original_sin_2.5.0.11-3.bin

It extracts a /tmp (files for the install shield) and /app (contains GameuxInstallHelper.dll  Support.ico ) folder, but not all the game files.

**Comment by dscharrer** [comment]
Here's a modified innoextract build: http://constexpr.org/innoextract/files/tmp/innoextract-1.5-rc1/

Additions:

* A `--gog-game-id` option to query the GOG.com game ID for the installer. (Maybe this should be changed to a more generic option to query registry keys. Either way, a way to extract all the registry keys is still planned.)
* `innoextract` will now warn you if there are `.bin` files with the Inno Setup or GOG naming scheme that aren't part of the installer.
* A `--gog` options to list/extract the RAR archives using `unrar` or `unar`. If both are available, `unrar` is used. Extracting multi-part RAR archives from GOG installers will temporarily symlink them to somewhere under the output directory as vanilla `unrar`/`unar` won't find the next archive with the GOG naming scheme. Not all `innoextract` options are supported for the RAR archives: With `unar` only `--list`, `--extract` and `--output-dir` work. With `unrar` `--timestamps none`, `--lowercase`, `--progress` and `--silent` also somewhat work.
* Other bug fixes & improvements since 1.4.

Any thoughts?

The last option is not in `master` yet, only in the `gog` branch.

**Comment by shmerl** [comment]
Sounds good. May be it would be good to add an option for extracting all .iss data as well?

**Comment by vv221** [comment]
Some news on the topic: GOG.com decided to drop the password encryption on their installers.
https://www.gog.com/forum/general/on_gnulinux_has_anyone_be_able_to_extract_the_rar_innosetup_installers/post470/?staff=yes

I didn’t check if it’s done yet.

**Comment by ssokolow** [comment]
As far as I can tell, it's not. There's been no indication that new installers have been released so far, either via the flagging system or via manual announcement in the ["What did just update?" thread](http://www.gog.com/forum/general/the_what_did_just_update_thread).

**Comment by dscharrer** [comment]
1.5 is out with the `--gog` option

**Comment by flflag** [comment]
> Sorry to reopen this but I want to list the contents of an old installer and I'm being asked for unrar or unar, I already have unrar on my PATH but innoextract keeps asking for it, I'm using Windows 10, I also tried copying the unrar.exe file to the program directory to no avail.

me too
