### ISSUE TITLE
warning when building on armhf

### ISSUE THREAD

**Issue by a-detiste** [dscharrer/innoextract#41]
This doesn't happen when building on amd64

```
/home/pi/innoextract/src/util/endian.hpp: In function ‘uint16_t util::detail::byteswap(uint16_t)’:
/home/pi/innoextract/src/util/endian.hpp:59:9: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  return bswap_16(value);
```

**Comment by dscharrer** [comment]
Huh, I get no such warning in [my `armv6j-hardfloat-linux-gnueabi` builds](http://constexpr.org/innoextract/buildlogs/branches/master/). What versions of innoextract, GLIBC and GCC did you use?

**Comment by a-detiste** [comment]
Here are the various versions used:

clang didn't complained

```
innoextract: git master

ii  libc6:armhf                            2.19-18
ii  libc6-dev:armhf                        2.19-18
ii  gcc                                    4:4.9.2-3
ii  gcc-4.9                                4.9.2-10
ii  gcc-4.9-base:armhf                     4.9.2-10
ii  libgcc-4.9-dev:armhf                   4.9.2-10
ii  libgcc1:armhf                          1:4.9.2-10
ii  clang-3.5                              1:3.5-10+rpi1
ii  libclang-common-3.5-dev                1:3.5-10+rpi1
ii  libclang1-3.5:armhf                    1:3.5-10+rpi1

boost 1.55.0.2

Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
```

**Comment by dscharrer** [comment]
Ah, I see why I don't get the warning now.

endian.hpp only uses bswap_16 for glibc ≥ 2.16, which is where this was fixed for x86 and x86_64. However, it's [still not fixed in the generic implementation used on ARM](https://sourceware.org/bugzilla/show_bug.cgi?id=15512).

I didn't get a warning with my ARM builds as I target an old glibc (2.14.1) for maximum binary comparability.

It's not a fatal error, and `-Wsign-conversion` is manually enabled for innoextract (`-Wall -Wextra` doesn't include it). However it seems GCC 4.8 finally added a 16-bit variant of `_builtin_bswap*`, so I may as well use that when available.

**Comment by a-detiste** [comment]
ACKed :smile:
