### ISSUE TITLE
Cannot extract GOG's "Quake: The Offering" with 1.6

### ISSUE THREAD

**Issue by duganchen** [dscharrer/innoextract#57]
➜ innoextract setup_quake_the_offering_2.0.0.6.exe
    Extracting "Quake - The Offering" - setup data version 5.5.0 (unicode)
     - "app/__support/app/hipnotic/config.cfg" (2.02 KiB) - overwritten
     - "app/__support/app/id1/config.cfg" (2 KiB) - overwritten
     - "app/__support/app/qw/config.cfg" (1.76 KiB) - overwritten
     - "app/__support/app/rogue/CONFIG.CFG" (2 KiB) - overwritten
     - "app/dosbox_quake.conf" (10.6 KiB) - overwritten
     - "app/dosbox_quake_single.conf" (1.04 KiB) - overwritten
     - "app/hipnotic/config.cfg" (2.02 KiB) - overwritten
     - "app/id1/config.cfg" (2 KiB) - overwritten
     - "app/qw/config.cfg" (1.76 KiB) - overwritten
     - "app/rogue/CONFIG.CFG" (2 KiB) - overwritten
     - "tmp/gog.ico" [temp] (67.6 KiB) - overwritten
    Could not create directory "app/Id1/glquake"
    Done with 1 error.

Extracting it into a ciopfs-mounted directory does work, and the installer has both "Id1" and "id1" directories, so this is likely a case sensitivity issue.

Passing "--collisions=overwrite" does not seem to make a difference.

**Comment by duganchen** [comment]
Oh, I see. I can use -L. Never mind.

**Comment by dscharrer** [comment]
It's still a bug that needs to be be fixed, but yes, `--lowercase` works around the problem.

**Comment by dscharrer** [comment]
Hi, this should now be fixed in the development code.

Please let me know if it still does not work for you with the [1.7-dev-2017-03-27 development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.7-dev-2017-03-27/) ([PPA](https://launchpad.net/~arx/+archive/ubuntu/snapshot/) / [OBS](http://software.opensuse.org//download.html?project=home%3Adscharrer%3Asnapshots&package=innoextract)).
