### ISSUE TITLE
Read installer from stdin, output to stdout

### ISSUE THREAD

**Issue by Mimoja** [dscharrer/innoextract#80]
Is there a idiomatic way to have innosetup run completely in memory?
Would including an --stdin flag be an option? I dont want to fork if others could benefit as well!

**Comment by Mimoja** [comment]
Sorry for that github massacre. Was not aware of that happening /0\

**Comment by dscharrer** [comment]
`innoextract` needs the input to be seekable. `innoextract` does already extract files in the order they are stored in the setup file, however setup headers are usually stored *after* the data so some seeking s required. Additionally, `innoextract` sometimes needs to read the setup headers twice because we version information stored in the installers is not always correct and we need to try multiple different formats to determine the correct one.

Also both input and output can be multiple files so stdin/stdout can't be used without wrapping things in an archive or some kind of protocol.

Why do you need `innoextract` to avoid the filesystem?

**Comment by jdpipe** [comment]
This would be a handy feature when downloading and extracting InnoSetup packages on the fly, for example in Github Actions builds, similar to what can be done using `bsdtar`. Perhaps if reading from standard input the tool could write to a temporary file using `_mktemp_s` or similar, do the extraction, and delete the file. That would provide user convenience if not the in-memory performance benefits.
